### ISSUE TITLE
Add Documentation for All SV2 Configurations

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/sri-docs#2]

**Comment by rrybarczyk** [comment]
We have several figures showing the various configurations that show the flexibility of the protocol.
Need to display these on the website, and also a more in-depth documentation.

**Comment by rrybarczyk** [comment]
Need to have the following configs:

- [x] A: `SV2 MD <- std chnl -> SV2 Proxy <- grp chnl -> SV2 Pool`, miner selected tx  (TP on pool + proxy)
  Most efficient config and has miner-selected txs, what everyone should aim to implement long-term.
- [x] B: `SV2 MD <- std chnl -> SV2 Proxy <- grp chnl -> SV2 Pool`, pool selected tx (TP on pool)
   Most efficient config and has pool-selected txs. 
- [x] C:`SV1 MD <- sv1 conn -> SV1/SV2 Proxy <- ext chnl -> SV2 Pool`, pool selected tx (TP on pool)
  MVP1 Config
- [ ] D:`SV1 MD <- sv1 conn -> SV1/SV2 Proxy <- ext chnl -> SV2 Pool`, miner selected tx (TP on pool + proxy)
  MVP2 Config
- [x] E: `SV2 MD <- std chnl ->  SV2 Pool`, pool selected tx (TP on pool)
  More efficient than SV1, but one of the least efficient configs. Important because currently the only SV2 production pool (Braiins), supports Standard Channels.
- [x] F: `SV2 MD <- std chnl -> SV2 Proxy <- std chnl -> SV2 Pool`, pool selected tx (TP on pool)
  Not recommended because if a miner is running a proxy, they should always favor group channels, but shown for the sake of completeness. 
- [ ] G: `SV2 MD <- std chnl -> SV2 Proxy <- grp chnl -> SV2 Proxy <- grp chnl -> SV2 Pool`, pool selected tx (TP on pool)
  Atypical configuration, but shown to highlight protocol flexibility.
- [ ] H: `SV2 MD <- std chnl -> SV2 Proxy <- grp chnl -> SV2 Proxy <- grp chnl -> SV2 Pool`, miner selected tx (TP on pool + proxy)
  Atypical configuration, but shown to highlight protocol flexibility.

**Comment by Aut0R3V** [comment]
@rrybarczyk I see that some of the pull requests have been merged already. Should this issue be closed then?
